export const states= {
    toasts: [],
    domains: [],
    listLoading: true,
    domainError: null,
    selectedDomains: new Set(),
    searchQuery: '',
    desecAuthStatus: '',
    desecAuthStatusError: '',
    isDrawerOpen: false,
    tokenInput: '',
    dbSuccess: false,
    dbError: '',
    saveAutoSyncSuccess: '',
    saveAutoSyncError: '',
    addDomainResponse: '',
    addButtonState: '',
    syncButtonState: '',
    registeredDomains: [],
    registeredDomainsError: '',
    registeredDomainsCode: '',
    lastSyncTimestampsSuccess: [],
    lastSyncTimestampsError: [],
    retainDomainCheck: "false",
    sortingBy: 'domain-name',
    sortingDirection: 'ASC',
    syncResponse: [],
    tokenStatus: true,
    formState: "",
    isFormOpen: true,
    emptyViewDescription: "The domain(s) that you are looking for doesn't/don't exist or there aren't any domains hosted on this Plesk instance.",
    emptyViewTitle: "No domains!",
    inputToken: "",
    refreshToggle: true,
    eulaDecision: true,
    privacyPolicyDialog: false
};

